apps/main/urls.py
# -*- coding: ISO-8859-1 -*-

from django.conf.urls import patterns, url, include
from apps.main import views

from django.conf.urls import patterns, url, include
from django.contrib.auth.forms import AuthenticationForm

urlpatterns = patterns('',
	url(r'^$', views.home, name="home"),
	url(r'^login/?$', 'django.contrib.auth.views.login',  {'template_name':'main/auth/login.html', 'authentication_form': AuthenticationForm}),
	url(r'^logout/?$', views.logout, name="logout"),
	url(r'^clientes/?$', views.clientes, name="clientes"),
	url(r'^consumos/?$', views.consumos, name="consumos"),
	url(r'^cliente/(?P<pk>[^/]+)/$',views.cliente, name="cliente"),
	url(r'^operarios/?$',views.operarios, name="operarios"),
	url(r'^operario/(?P<pk>[^/]+)/$',views.operario, name="operario")
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('apps.main.urls', namespace="main")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('apps.api.urls')),
)

from django.conf import settings

urlpatterns += patterns('',
   (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

apps/main/models.py
# -*- coding: ISO-8859-1 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator

from django.contrib.auth.models import (
	BaseUserManager,AbstractUser, AbstractBaseUser, UserManager
)

from django.contrib.auth.hashers import (
	check_password, make_password, is_password_usable, UNUSABLE_PASSWORD
)

from django.contrib.auth.models import User

from datetime import date
from datetime import datetime

from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.db.models.signals import post_save

#------------------------------------------------------------------------
#	Cliente
#------------------------------------------------------------------------

class Cliente(models.Model):

	nombres = models.CharField(max_length=255)
	apellidos = models.CharField(max_length=255)
	numero_de_suministro = models.IntegerField()

	def __unicode__(self):
		return self.nombres + " " + self.apellidos

	class Meta:
		db_table = "Cliente"
		verbose_name = "cliente"
		verbose_name_plural = "clientes"


#------------------------------------------------------------------------
#	Operario
#------------------------------------------------------------------------

class Operario(models.Model):

	user = models.OneToOneField(User)
	nombres = models.CharField(max_length=255)
	apellidos = models.CharField(max_length=255)
	codigo = models.IntegerField()

	def __unicode__(self):
		return self.nombres + " " + self.apellidos
		
	class Meta:
		db_table = "Operario"
		verbose_name = "operario"
		verbose_name_plural = "operarios"


#------------------------------------------------------------------------
#	Consumo
#------------------------------------------------------------------------

class Consumo(models.Model):

	consumo = models.DecimalField(_("consumption"),decimal_places=6,max_digits=12,blank=False)
	cliente = models.ForeignKey(Cliente,verbose_name=_('client'))
	operario = models.ForeignKey(Operario,verbose_name=_('operario'))
 	fecha = models.DateField(auto_now = True)

 	def __unicode__(self):
 		return "Registro de consumo del cliente " + self.cliente.nombres

 	class Meta:
 		db_table = "Consumo"
 		verbose_name = "consumo"
 		verbose_name_plural = "consumos"


@receiver(post_save, sender=User)
def create_auth_token_baseuser(sender, instance=None, created=False, **kwargs):
	if created:
		Token.objects.create(user=instance)

apps/main/views.py
#!--coding:utf-8--#

from django.db import models
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from django.core.mail import send_mail
from django.forms.models import model_to_dict
from django.contrib import messages
from pprint import pprint
from datetime import datetime

from apps.main.models import *

from django.views.decorators.csrf import ensure_csrf_cookie

#---------------------------------------------------------------
#	INDEX
#---------------------------------------------------------------

@ensure_csrf_cookie
def home(request):
	if request.user.is_authenticated():
		clientes = Cliente.objects.all()
		return render(request,"main/index.html",{'clientes':clientes})
	else:
		return render(request,"index.html")

#---------------------------------------------------------------
#	LOGOUT
#---------------------------------------------------------------

from django.contrib.auth import authenticate
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout, get_user_model
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

def logout(request):
	auth_logout(request)
	request.session.clear()
	return HttpResponseRedirect("/")

def clientes(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/")

	clientes  = Cliente.objects.all()
	return render(request, "main/clientes.html",{'clientes':clientes})

def consumos(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/")

	consumos  = Consumo.objects.all()
	return render(request, "main/consumos.html",{'consumos':consumos})

def cliente(request,pk=None):
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/")

	cliente = Cliente.objects.get(id=pk)
	return render(request, "main/cliente.html",{'cliente':cliente})

def operarios(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/")

	operarios = Operario.objects.all()
	return render(request, "main/operarios.html",{'operarios':operarios})

def operario(request,pk=None):
	if not request.user.is_authenticated():
		return HttpResponseRedirect("/")

	operario = Operario.objects.get(id=pk)
	return render(request, "main/operario.html",{'operario':operario})

templates/main/cliente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{STATIC_URL}}ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="{{STATIC_URL}}ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">LuzBell</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <a href="#" class="navbar-link">{{user.operario.nombres}} {{user.operario.apellidos}}</a> | 
              <a href="/logout" class="navbar-link"> Salir</a>
            </p>
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/clientes">Clientes</a></li>
              <li><a href="/consumos">Consumos</a></li>
              <li><a href="/operarios">Operarios</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">{{cliente.nombres}} {{cliente.apellidos}}</li>
              <li><strong>Número de suministro :</strong> {{cliente.numero_de_suministro}}</li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          
            <h2> Consumos </h2>
            <hr/>

            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Operario</th>
                  <th>Consumo</th>
                  <th>Fecha</th>
                </tr>
              </thead>
              <tbody>

                {% for consumo in cliente.consumo_set.all %}
                  <tr>
                    <td>{{consumo.id}}</td>
                    <td>{{consumo.cliente.nombres}} {{consumo.cliente.apellidos}}</td>
                    <td>{{consumo.consumo}}</td>
                    <td>{{consumo.fecha}}</td>
                  </tr>
                {% endfor %}

              </tbody>
            </table>


        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Daniel Flores 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{STATIC_URL}}js/jquery.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-transition.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-alert.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-modal.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-dropdown.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-scrollspy.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tab.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tooltip.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-popover.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-button.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-collapse.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-carousel.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-typeahead.js"></script>

  </body>
</html>

templates/main/clientes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{STATIC_URL}}ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="{{STATIC_URL}}ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">LuzBell</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <a href="#" class="navbar-link">{{user.operario.nombres}} {{user.operario.apellidos}}</a> | 
              <a href="/logout" class="navbar-link"> Salir</a>
            </p>
            <ul class="nav">
              <li ><a href="/">Home</a></li>
              <li class="active"><a href="/clientes">Clientes</a></li>
              <li><a href="/consumos">Consumos</a></li>
              <li><a href="/operarios">Operarios</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Objetos</li>
              <li class="active"><a href="/clientes">Clientes</a></li>
              <li><a href="/consumos">Consumos</a></li>
              <li><a href="/operarios">Operarios</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          

            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Nombres</th>
                  <th>Apellidos</th>
                  <th>Número de suministro</th>
                </tr>
              </thead>
              <tbody>

                {% for cliente in clientes %}
                  <tr>
                    <td><a href="/cliente/{{cliente.id}}/">{{cliente.id}}</a></td>
                    <td>{{cliente.nombres}}</td>
                    <td>{{cliente.apellidos}}</td>
                    <td>{{cliente.numero_de_suministro}}</td>
                  </tr>
              {% endfor %}

              </tbody>
            </table>

            

        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Daniel Flores 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{STATIC_URL}}js/jquery.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-transition.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-alert.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-modal.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-dropdown.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-scrollspy.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tab.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tooltip.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-popover.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-button.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-collapse.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-carousel.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-typeahead.js"></script>

  </body>
</html>

templates/main/consumos.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{STATIC_URL}}ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="{{STATIC_URL}}ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">LuzBell</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <a href="#" class="navbar-link">{{user.operario.nombres}} {{user.operario.apellidos}}</a> | 
              <a href="/logout" class="navbar-link"> Salir</a>
            </p>
            <ul class="nav">
              <li ><a href="/">Home</a></li>
              <li><a href="/clientes">Clientes</a></li>
              <li class="active"><a href="/consumos">Consumos</a></li>
              <li><a href="/operarios">Operarios</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Objetos</li>
              <li><a href="/clientes">Clientes</a></li>
              <li class="active"><a href="/consumos">Consumos</a></li>
              <li><a href="/operarios">Operarios</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          

            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Cliente</th>
                  <th>Consumo</th>
                  <th>Fecha</th>
                  <th>Operario</th>
                </tr>
              </thead>
              <tbody>

                {% for consumo in consumos %}
                  <tr>
                    <td>{{consumo.id}}</td>
                    <td><a href="/cliente/{{consumo.cliente.id}}/">{{consumo.cliente.nombres}} {{consumo.cliente.apellidos}}</a></td>
                    <td>{{consumo.consumo}}</td>
                    <td>{{consumo.fecha}}</td>
                    <td><a href="/operario/{{consumo.operario.id}}/">{{consumo.operario}}</a></td>
                  </tr>
                {% endfor %}

              </tbody>
            </table>


        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Daniel Flores 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{STATIC_URL}}js/jquery.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-transition.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-alert.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-modal.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-dropdown.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-scrollspy.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tab.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tooltip.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-popover.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-button.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-collapse.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-carousel.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-typeahead.js"></script>

  </body>
</html>

templates/main/operario.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{STATIC_URL}}ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="{{STATIC_URL}}ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">LuzBell</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
             <a href="#" class="navbar-link">{{user.operario.nombres}} {{user.operario.apellidos}}</a> | 
              <a href="/logout" class="navbar-link"> Salir</a>
            </p>
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/clientes">Clientes</a></li>
              <li><a href="/consumos">Consumos</a></li>
              <li><a href="/operarios">Operarios</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">{{operario.nombres}} {{operario.apellidos}}</li>
              <li><strong>Código :</strong> {{operario.codigo}}</li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
            
            <h2> Consumos registrados </h2>
            <hr/>

            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Cliente</th>
                  <th>Consumo</th>
                  <th>Fecha</th>
                </tr>
              </thead>
              <tbody>

                {% for consumo in operario.consumo_set.all %}
                  <tr>
                    <td>{{consumo.id}}</td>
                    <td>{{consumo.cliente.nombres}} {{consumo.cliente.apellidos}}</td>
                    <td>{{consumo.consumo}}</td>
                    <td>{{consumo.fecha}}</td>
                  </tr>
                {% endfor %}

              </tbody>
            </table>


        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Daniel Flores 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{STATIC_URL}}js/jquery.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-transition.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-alert.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-modal.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-dropdown.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-scrollspy.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tab.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-tooltip.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-popover.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-button.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-collapse.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-carousel.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-typeahead.js"></script>

  </body>
</html>